name: ftcmanageapp
description: "An app to manage your ftc team"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.0.3
  provider: ^6.0.0
  flame:  ^1.34.0
  url_launcher: ^6.3.0
  gamepads: ^0.1.6
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.5
  pdfrx: ^1.0.80
  fl_chart: ^0.70.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - files/images/decode_background.png
    - files/images/logo.png
    - files/resources/DECODE_Competition_Manual_TU18.pdf
    - files/resources/qeustions_pit_interviews.json
